## Question 1: Compare and contrast NLTK and spaCy in terms of features, ease of use, and performance.

- NLTK and spaCy are two widely used Python libraries for Natural Language Processing (NLP). Although both perform similar NLP tasks (tokenization, POS tagging, NER, etc.), they differ in features, ease of use, and performance.

1. Overview of NLTK and spaCy

NLTK (Natural Language Toolkit): A comprehensive NLP library mainly designed for education, research, and experimentation. It provides many algorithms and linguistic resources for studying language processing.

spaCy: A modern NLP library designed for production-level applications, focusing on speed, efficiency, and easy deployment of NLP pipelines.

2. Feature Comparison #1.NLTK  2.spaCy

* Library Type
1. Research and educational toolkit
2. Production-ready NLP framework
* Tokenization
1. Multiple tokenizers (regex, Punkt, etc.)
2. Fast rule-based tokenizer
* POS Tagging
1. Multiple rule-based and statistical taggers
2. Deep learning-based tagging
* Named Entity Recognition
1. Available but less optimized
2. Highly accurate pre-trained NER
* Corpora & Resources
1. Large collection (WordNet, corpora)
2. Smaller built-in resources

NLTK provides more linguistic resources and algorithms, while spaCy focuses on efficient pipelines and ready-to-use NLP components.

3. Ease of Use

- NLTK

Requires manual configuration of NLP tasks.

Users often combine multiple modules for tokenization, tagging, etc.

Better for learning NLP concepts step by step.

from nltk.tokenize import word_tokenize
text = "I love NLP"
tokens = word_tokenize(text)

- spaCy

Provides a simple and consistent API.

Many tasks work directly with pre-trained models.

import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp("I love NLP")
tokens = [token.text for token in doc]

4. Performance Comparison  #1.NLTK  2.spaCy

* Speed
1. Slower
2. Much faster
* Implementation
1. Pure Python
2. Optimized using Cython
* Large dataset handling
1. Not ideal
2. Designed for large-scale processing
* Real-time applications
1. Limited
2. Suitable for APIs and chatbots

# Question 2: What is TextBlob and how does it simplify common NLP tasks like sentiment analysis and translation?

- TextBlob is a Python library for Natural Language Processing (NLP) that provides a simple and easy-to-use API for performing common text processing tasks. It is built on top of libraries such as NLTK and Pattern, which means it uses their functionality internally but presents it in a much simpler way for users.

TextBlob is mainly used by beginners and developers who want to perform NLP tasks quickly without writing complex code.

1. Features of TextBlob

TextBlob provides many NLP functionalities, including:

Tokenization (splitting text into words or sentences)

Part-of-Speech (POS) tagging

Noun phrase extraction

Sentiment analysis

Language translation

Spell checking

Because of its simple syntax, TextBlob is widely used for basic NLP tasks and rapid prototyping.

2. How TextBlob Simplifies NLP Tasks
1. Sentiment Analysis

Sentiment analysis determines whether a piece of text expresses positive, negative, or neutral emotion.

TextBlob makes this process extremely simple by providing a built-in sentiment analyzer that returns:

Polarity (range: −1 to +1)

−1 → negative sentiment

0 → neutral sentiment

+1 → positive sentiment

Subjectivity (range: 0 to 1)

0 → objective statement

1 → subjective opinion

3. Translation

TextBlob can also translate text between languages using built-in translation support.


In [ ]:

from googletrans import Translator

text_to_translate = "I love programming"

translator = Translator()
translated = translator.translate(text_to_translate, dest="fr")

print(translated.text)

J'adore la programmation


#Question 3: Explain the role of Standford NLP in academic and industry NLP Projects.

- Stanford NLP plays a dual role: in academia, it drives cutting-edge research and provides widely used educational resources, while in industry, its tools like CoreNLP, Stanza, and GloVe power production-level NLP applications across domains such as chatbots, information extraction, and sentiment analysis.

1. Role in Academic Projects

* Research Leadership:

The Stanford NLP Group is one of the most influential academic teams in computational linguistics, contributing to foundational work in parsing, sentiment analysis, and machine learning for language.

* Educational Resources:

Provides tutorials, seminars, and open-source software for students and researchers.

CoreNLP and Stanza are often used in coursework and theses to demonstrate NLP concepts.

* Corpora & Models:

Developed GloVe embeddings, a major advancement in word representation widely cited in academic papers.

Offers multilingual pipelines (Stanza supports 60+ languages) for comparative linguistic studies.

* Interdisciplinary Impact:
Research extends into computational social science and cognitive science, helping academics study language in psychology, sociology, and political science.

2.  Role in Industry Projects

* Production-Ready Tools:

Stanford CoreNLP: A Java-based toolkit offering tokenization, POS tagging, dependency parsing, named entity recognition, and sentiment analysis.

 Stanza: A Python library with neural network–based NLP pipelines, designed for easy integration into modern workflows.

* Enterprise Applications:

Used in chatbots, customer support systems, and document classification.

Supports retrieval-augmented generation (RAG) and specialized workflows in AI systems.

* Scalability:
CoreNLP is robust for large-scale text processing, while Stanza provides deep learning–based pipelines suitable for modern industry needs.

* Integration:
Works with other ML frameworks (TensorFlow, PyTorch) and can be embedded into production systems.

#Question 4: Describe the architecture and functioning of a Recurrent Natural Network (RNN).

- Recurrent Neural Networks (RNNs) are neural architectures designed for sequential data, where connections form directed cycles to maintain memory across time steps. They process inputs like text or time series by passing hidden states forward, enabling context retention unlike feedforward networks.

* Architecture of RNN

Input Layer: Accepts sequential data (e.g., words in a sentence, stock prices over time).

Hidden Layer(s):

Core of the RNN where the hidden state is updated at each time step.

Hidden state
ℎ
𝑡
 depends on both the current input
𝑥
𝑡
 and the previous hidden state
ℎ
𝑡
−
1
.

Formula:

ℎ
𝑡
=
𝑓
(
𝑊
𝑥
ℎ
⋅
𝑥
𝑡
+
𝑊
ℎ
ℎ
⋅
ℎ
𝑡
−
1
+
𝑏
ℎ
)
where
𝑓
 is an activation function (commonly tanh or ReLU).

Output Layer: Produces predictions at each time step (e.g., next word, sentiment score).

Weights Sharing: Unlike feedforward networks, RNNs share weights across time steps, making them efficient for sequential learning.

* Functioning of RNN
1. Sequential Processing:

Inputs are fed one at a time in sequence.

Each step updates the hidden state, which acts as memory.

2. Context Preservation:

The hidden state carries information from previous steps, allowing the network to “remember” past context.

Example: Predicting the next word in “I love data ___” requires remembering “I love data.”

3. Output Generation:

At each time step, the network can produce an output (many-to-many) or only after the full sequence (many-to-one).

# Question 5: What is the key difference between LSTM and GRU networks in NLP applications?

- LSTM and GRU are advanced RNN variants that solve vanishing gradients, but differ fundamentally in gating mechanisms and efficiency. Key difference: LSTM uses 3 gates + separate cell state (4x parameters); GRU uses 2 gates + merged state (~75% LSTM parameters).

* Architectural Differences
1. LSTM
2. GRU

 Structure ▶
1. More complex
2. Simpler

Number of Gates ▶
1. 3 gates
2. 2 gates

Memory Cell ▶
1. Has a separate memory cell
2. No separate memory cell

Training Speed ▶
1. Slower
2. Faster

Parameters ▶
1. More parameters
2. Fewer parameters

Performance ▶
1. Good for long sequences
2. Good for moderate sequences

* LSTM Architecture

LSTM uses three gates to control information flow:

Forget Gate – decides what information to discard

Input Gate – decides what new information to store

Output Gate – decides what information to send to the output

Because of these gates, LSTM can remember long-term dependencies in text sequences.

Example use:

Language translation

Text generation

Speech recognition

* GRU Architecture

GRU simplifies the LSTM structure by using two gates:

Update Gate – controls how much past information to keep

Reset Gate – decides how to combine new input with past memory

GRU merges the cell state and hidden state, which reduces complexity and speeds up training.


In [1]:
# Question 6: Write a Python program using TextBlob to perform sentiment analysis on the following paragraph of text:

"""I had a great experience using the new mobile banking app.
The interface is intuitive, and customer support was quick to resolve my issue.
However, the app did crash once during a transaction, which was frustrating"""


!pip install textblob
from textblob import TextBlob

text = """I had a great experience using the new mobile banking app.
The interface is intuitive, and customer support was quick to resolve my issue.
However, the app did crash once during a transaction, which was frustrating."""

blob = TextBlob(text)

sentiment = blob.sentiment

print("Polarity:", sentiment.polarity)
print("Subjectivity:", sentiment.subjectivity)

Polarity: 0.21742424242424244
Subjectivity: 0.6511363636363636


In [5]:
# Question 7: Given the sample paragraph below, perform string tokenization and frequency distribution using Python and NLTK:

"""Natural Language Processing (NLP) is a fascinating field that combines linguistics,
computer science, and artificial intelligence. It enables machines to understand,
interpret, and generate human language. Applications of NLP include chatbots,
sentiment analysis, and machine translation. As technology advances, the role of NLP
in modern solutions is becoming increasingly critical."""

!pip install nltk

import nltk
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist
from nltk.probability import FreqDist

nltk.download('punkt')
nltk.download('punkt_tab')

text = """Natural Language Processing (NLP) is a fascinating field that combines linguistics,
computer science, and artificial intelligence. It enables machines to understand,
interpret, and generate human language. Applications of NLP include chatbots,
sentiment analysis, and machine translation. As technology advances, the role of NLP
in modern solutions is becoming increasingly critical."""

tokens = word_tokenize(text)
print("Tokens:")
print(tokens)

freq_dist = FreqDist(tokens)

print("\nFrequency Distribution:")

for word, freq in freq_dist.items():
    print(f"{word}: {freq}")


Tokens:
['Natural', 'Language', 'Processing', '(', 'NLP', ')', 'is', 'a', 'fascinating', 'field', 'that', 'combines', 'linguistics', ',', 'computer', 'science', ',', 'and', 'artificial', 'intelligence', '.', 'It', 'enables', 'machines', 'to', 'understand', ',', 'interpret', ',', 'and', 'generate', 'human', 'language', '.', 'Applications', 'of', 'NLP', 'include', 'chatbots', ',', 'sentiment', 'analysis', ',', 'and', 'machine', 'translation', '.', 'As', 'technology', 'advances', ',', 'the', 'role', 'of', 'NLP', 'in', 'modern', 'solutions', 'is', 'becoming', 'increasingly', 'critical', '.']

Frequency Distribution:
Natural: 1
Language: 1
Processing: 1
(: 1
NLP: 3
): 1
is: 2
a: 1
fascinating: 1
field: 1
that: 1
combines: 1
linguistics: 1
,: 7
computer: 1
science: 1
and: 3
artificial: 1
intelligence: 1
.: 4
It: 1
enables: 1
machines: 1
to: 1
understand: 1
interpret: 1
generate: 1
human: 1
language: 1
Applications: 1
of: 2
include: 1
chatbots: 1
sentiment: 1
analysis: 1
machine: 1
translatio

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [6]:
# Question 8: Implement a basic LSTM model in Keras for a text classification task using the following dummy dataset. Your model should classify sentences as either positive (1) or negative (0).
# Dataset
"""texts = [
“I love this project”, #Positive
“This is an amazing experience”, #Positive
“I hate waiting in line”, #Negative
“This is the worst service”, #Negative
“Absolutely fantastic!” #Positive
]
labels = [1, 1, 0, 0, 1]"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt

# 1. Dataset
texts = [
    "I love this project",
    "This is an amazing experience",
    "I hate waiting in line",
    "This is the worst service",
    "Absolutely fantastic!"
]
labels = np.array([1, 1, 0, 0, 1])

print("Dataset:")
for text, label in zip(texts, labels):
    sentiment = "POSITIVE" if label == 1 else "NEGATIVE"
    print(f"  '{text}' → {sentiment}")

# 2. TEXT PREPROCESSING
# Tokenization & Vocabulary
tokenizer = Tokenizer(num_words=100, oov_token="<OOV>")
tokenizer.fit_on_texts(texts)
vocab_size = len(tokenizer.word_index) + 1
print(f"\nVocab size: {vocab_size}")
print("Word index:", tokenizer.word_index)

# Convert to sequences
sequences = tokenizer.texts_to_sequences(texts)
print("\nSequences:", sequences)

# Padding (fixed length)
max_length = 10
padded_sequences = pad_sequences(sequences, maxlen=max_length, padding='post', truncating='post')
print("\nPadded sequences:\n", padded_sequences)

# 3. MODEL ARCHITECTURE
model = Sequential([
    Embedding(vocab_size, 32, input_length=max_length),  # Embeddings
    LSTM(64, dropout=0.3, recurrent_dropout=0.3),        # LSTM layer
    Dropout(0.5),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')                       # Binary classification
])

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

# 4. TRAINING
print("\nTRAINING...")
history = model.fit(
    padded_sequences, labels,
    epochs=20,
    batch_size=8,
    validation_split=0.2,  # 1 sample validation
    verbose=1
)

# 5. EVALUATION & PREDICTIONS
print("\nPREDICTIONS:")
for i, seq in enumerate(padded_sequences):
    pred = model.predict(seq.reshape(1, -1), verbose=0)[0][0]
    pred_label = 1 if pred > 0.5 else 0
    actual = labels[i]
    print(f"Text: '{texts[i]}'")
    print(f"  Actual: {actual}, Predicted: {pred_label:.0f} (prob: {pred:.3f})")

print("\nFinal Accuracy:", max(history.history['val_accuracy']))



Dataset:
  'I love this project' → POSITIVE
  'This is an amazing experience' → POSITIVE
  'I hate waiting in line' → NEGATIVE
  'This is the worst service' → NEGATIVE
  'Absolutely fantastic!' → POSITIVE

Vocab size: 19
Word index: {'<OOV>': 1, 'this': 2, 'i': 3, 'is': 4, 'love': 5, 'project': 6, 'an': 7, 'amazing': 8, 'experience': 9, 'hate': 10, 'waiting': 11, 'in': 12, 'line': 13, 'the': 14, 'worst': 15, 'service': 16, 'absolutely': 17, 'fantastic': 18}

Sequences: [[3, 5, 2, 6], [2, 4, 7, 8, 9], [3, 10, 11, 12, 13], [2, 4, 14, 15, 16], [17, 18]]

Padded sequences:
 [[ 3  5  2  6  0  0  0  0  0  0]
 [ 2  4  7  8  9  0  0  0  0  0]
 [ 3 10 11 12 13  0  0  0  0  0]
 [ 2  4 14 15 16  0  0  0  0  0]
 [17 18  0  0  0  0  0  0  0  0]]


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)


TRAINING...
Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - accuracy: 0.5000 - loss: 0.6945 - val_accuracy: 1.0000 - val_loss: 0.6787
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.7500 - loss: 0.6918 - val_accuracy: 1.0000 - val_loss: 0.6793
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.5000 - loss: 0.6982 - val_accuracy: 1.0000 - val_loss: 0.6795
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.5000 - loss: 0.6926 - val_accuracy: 1.0000 - val_loss: 0.6795
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - accuracy: 0.5000 - loss: 0.6952 - val_accuracy: 1.0000 - val_loss: 0.6795
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.7500 - loss: 0.6917 - val_accuracy: 1.0000 - val_loss: 0.6795
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.5000 - loss: 0.6911 - val_accuracy: 1.0000 - val_loss: 0.6796
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - accuracy: 0.5000 - loss: 0.6902 - val_accuracy: 1.0000 -

In [8]:
# Question 9: Using spaCy, build a simple NLP pipeline that includes tokenization, lemmatization, and entity recognition. Use the following paragraph as your dataset:

"""Homi Jehangir Bhaba was an Indian nuclear physicist who played a key role in the
development of India’s atomic energy program. He was the founding director of the Tata
Institute of Fundamental Research (TIFR) and was instrumental in establishing the
Atomic Energy Commission of India."""


!pip install spacy

# Download English model
!python -m spacy download en_core_web_sm

import spacy

# Load NLP model
nlp = spacy.load("en_core_web_sm")

# Dataset paragraph
text = """Homi Jehangir Bhabha was an Indian nuclear physicist who played a key role in the
development of India's atomic energy program. He was the founding director of the Tata
Institute of Fundamental Research (TIFR) and was instrumental in establishing the
Atomic Energy Commission of India."""

# Process the text
doc = nlp(text)

# 1. Tokenization + Lemmatization
print("TOKENS AND LEMMAS:")
for token in doc:
    print(token.text, "->", token.lemma_)

# 2. Named Entity Recognition
print("\nNAMED ENTITIES:")
for ent in doc.ents:
    print(ent.text, ":", ent.label_)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 69.2 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
TOKENS AND LEMMAS:
Homi -> Homi
Jehangir -> Jehangir
Bhabha -> Bhabha
was -> be
an -> an
Indian -> indian
nuclear -> nuclear
physicist -> physicist
who -> who
played -> play
a -> a
key -> key
role -> role
in -> in
the -> the

 -> 

development -> development
of -> of
India -> India
's -> 's
atomic -> atomic
energy -> energy
program -> program
. -> .
He -> he
was -> be
the -> the
founding -> found
director -> director
of -> of
the -> the
Tata -> Tata

 -> 

Institute -> Institute
of -> of
Fundamental -> Fundamental
Research -> Research
( -> (
TIFR -> TIFR
) -> )
and -> and
was 

In [11]:
# Question 10: You are working on a chatbot for a mental health platform. Explain how you would leverage LSTM or GRU networks along with libraries like spaCy or Stanford NLP to understand and respond to user input effectively. Detail your architecture, data preprocessing pipeline, and any ethical considerations.

# Install libraries
!pip install spacy tensorflow
!python -m spacy download en_core_web_sm

import spacy
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

# Example dataset
texts = [
    "I feel very sad today",
    "I am extremely happy",
    "I feel stressed about my exams",
    "Life is wonderful",
    "I feel lonely"
]

labels = np.array([0, 1, 0, 1, 0])  # 0 = negative emotion, 1 = positive emotion

# Preprocessing with spaCy
clean_texts = []
for text in texts:
    doc = nlp(text.lower())
    tokens = [token.lemma_ for token in doc if not token.is_stop and token.is_alpha]
    clean_texts.append(" ".join(tokens))

print("Cleaned Texts:", clean_texts)

# Tokenization
tokenizer = Tokenizer()
tokenizer.fit_on_texts(clean_texts)

seq = tokenizer.texts_to_sequences(clean_texts)

# Padding
X = pad_sequences(seq, maxlen=5)
y = labels

# Build LSTM model
model = Sequential()
model.add(Embedding(input_dim=50, output_dim=8, input_length=5))
model.add(LSTM(16))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train model
model.fit(X, y, epochs=20, verbose=0)

# Test input
test = ["I feel very anxious"]
doc = nlp(test[0].lower())
tokens = [t.lemma_ for t in doc if not t.is_stop and t.is_alpha]
clean_test = " ".join(tokens)

seq_test = tokenizer.texts_to_sequences([clean_test])
pad_test = pad_sequences(seq_test, maxlen=5)

prediction = model.predict(pad_test)

print("\nUser Input:", test[0])
print("Prediction (probability of positive):", prediction)


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 75.1 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
Cleaned Texts: ['feel sad today', 'extremely happy', 'feel stressed exam', 'life wonderful', 'feel lonely']


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 292ms/step

User Input: I feel very anxious
Prediction (probability of positive): [[0.4772985]]
